default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: utf8
  username: joban
  password: password
  database: trendz_database
  host: localhost
test:
  <<: *default
  database: test_trendz_database
